import os
import git
from llm_client import SecurityAgentClient 
from github import Github 

class RemediationActor:
    def __init__(self, container):
        self.container = container
        self.llm = SecurityAgentClient()

    def get_pom_content(self):
        result = self.container.exec_run("cat pom.xml", workdir="/home/agent/workspace")
        return result.output.decode()

    def autonomous_patch(self, ghsa_ids, build_error=None):
        pom_content = self.get_pom_content()
        plan = self.llm.get_remediation_plan(ghsa_ids, pom_content, build_error)
        
        if not plan:
            return False 
            
        target = plan.get('target_version')
        parent = plan.get('parent_version')
        print(f"🤖 AI Decision: Upgrade to {target} (Parent: {parent})")
        
        python_patch = f"""
import xml.etree.ElementTree as ET
ET.register_namespace('', 'http://maven.apache.org/POM/4.0.0')
tree = ET.parse('pom.xml')
root = tree.getroot()
ns = {{'mvn': 'http://maven.apache.org/POM/4.0.0'}}

v = root.find('mvn:version', ns)
if v is not None: v.text = '{target}'

p_v = root.find('mvn:parent/mvn:version', ns)
if p_v is not None and '{parent}':
    p_v.text = '{parent}'

tree.write('pom.xml', encoding='UTF-8', xml_declaration=True)
"""
        escaped_script = python_patch.replace('"', '\\"').replace("'", "'\\''")
        self.container.exec_run(f"python3 -c \"{escaped_script}\"", workdir="/home/agent/workspace")
        return True

    def fix_java_version_conflict(self):
        print("🛠️  Agent is applying a deep patch to pom.xml...")
        patch_script = (
            "sed -i 's/<source>.*<\\/source>/<source>17<\\/source>/g' pom.xml && "
            "sed -i 's/<target>.*<\\/target>/<target>17<\\/target>/g' pom.xml && "
            "sed -i '/<compilerArgs>/,/<\\/compilerArgs>/d' pom.xml"
        )
        self.container.exec_run(f"bash -c \"{patch_script}\"", workdir="/home/agent/workspace")

    def apply_security_patch(self, cve_list):
        print(f"🧬 Remediating: {', '.join(cve_list)}")
        python_patch = """
import xml.etree.ElementTree as ET

ET.register_namespace('', 'http://maven.apache.org/POM/4.0.0')
tree = ET.parse('pom.xml')
root = tree.getroot()
ns = {'mvn': 'http://maven.apache.org/POM/4.0.0'}

version_node = root.find('mvn:version', ns)
if version_node is not None:
    version_node.text = '2.13.4.2'

parent_version = root.find('mvn:parent/mvn:version', ns)
if parent_version is not None:
    parent_version.text = '2.13.4'

tree.write('pom.xml', encoding='UTF-8', xml_declaration=True)
"""
        escaped_script = python_patch.replace('"', '\\"').replace("'", "'\\''")
        self.container.exec_run(f"python3 -c \"{escaped_script}\"", workdir="/home/agent/workspace")

    def create_pull_request(self, local_repo_path, ghsa_ids):
        repo = git.Repo(local_repo_path)
        new_branch = f"fix/{'-'.join(ghsa_ids[:2])}"
        
        print(f"🌿 Preparing branch: {new_branch}")
        current = repo.create_head(new_branch, force=True)
        current.checkout()
        repo.git.add(A=True)
        repo.index.commit(f"Security: Automated remediation for {ghsa_ids}")

        print(f"⬆️ Pushing branch to origin...")
        origin = repo.remote(name='origin')
        origin.push(new_branch, force=True)

        token = os.getenv("GITHUB_TOKEN")
        if not token:
            print("❌ GITHUB_TOKEN not found. PR skipped.")
            return

        g = Github(token)
        remote_url = origin.url
        
        if "github.com:" in remote_url: 
            repo_full_name = remote_url.split("github.com:")[-1].replace(".git", "")
        else: 
            repo_full_name = remote_url.split("github.com/")[-1].replace(".git", "")

        gh_repo = g.get_repo(repo_full_name)
        
        # --- DYNAMICALLY RESOLVE DEFAULT BRANCH ---
        # This fixes the previous NameError and the 422 error[cite: 5]
        base_branch = gh_repo.default_branch 
        print(f"🎯 Target base branch resolved: {base_branch}")

        body = (
            "## 🛡️ Automated Security Remediation\n"
            f"This PR was generated by the **Sentinel Agent** to address: {', '.join(ghsa_ids)}.\n\n"
            "### 🧪 Verification\n"
            "- [x] Version bumped in `pom.xml`\n"
            "- [x] Verified with `mvn clean compile` in an isolated sandbox.\n"
        )

        try:
            pr = gh_repo.create_pull(
                title=f"Security: Fix {ghsa_ids[0]} and others",
                body=body,
                head=new_branch,
                base=base_branch 
            )
            print(f"🚀 SUCCESS: PR Created at {pr.html_url}")
        except Exception as e:
            print(f"⚠️ PR creation failed: {e}")